# -----------------------------------------------------------------------------
# Name:        data_models.py
# Purpose:    To manipulate data generated by the sensors in the SEA Program
# Authors:     aric.sanders@nist.gov
# Created:     2025/08/25
# License:     NIST License
# -----------------------------------------------------------------------------
"""data_models.py is a module that adds functionality to https://github.com/usnistgov/nasctn-sea-ingest. The data models are intended to lower the barrier of entry to plotting and data analysis
"""
# -----------------------------------------------------------------------------
# Standard Imports
import os 
#import numexpr as ne
import tarfile
import json
import re
import datetime
import dateutil as dtu
import datetime as dt
import zipfile
import shutil
# -----------------------------------------------------------------------------
# Third Party Imports
import numpy as np
import pandas as pd
import sea_ingest
import scipy.signal as signal

import warnings
warnings.filterwarnings("ignore")
# -----------------------------------------------------------------------------
# Module Constants
SENSOR_COMMON_NAMES = {"seadog03.its.ntia.gov":"Midway",
                       "seadog04.its.ntia.gov":"HU",
                       "seadog05.its.ntia.gov":"NIT",
                       "seadog07.its.ntia.gov":"GMM",
                       "seadog14.its.ntia.gov":"GMM",
                       "seadog08.its.ntia.gov":"Pendleton",
                       "seadog09.its.ntia.gov":"Catalina-Omni",
                       "seadog19.its.ntia.gov":"Catalina-Directional",
                       "seadog12.its.ntia.gov":"Catalina-Omni",
                       "seadog22.its.ntia.gov":"Catalina-Directional",
                       "seadog06.its.ntia.gov":"CBBT-Omni",
                       "seadog16.its.ntia.gov":"CBBT-Directional",
                       "seadog10.its.ntia.gov":"Oceana",
                       "seadog32.its.ntia.gov":"PtLoma-Omni",
                       "seadog42.its.ntia.gov":"PtLoma-Directional"}
#SENSOR_IP_NAMES = {value:key for key,value in SENSOR_COMMON_NAMES.items() }
SENSOR_IDS = {"seadog03.its.ntia.gov":4,
                       "seadog04.its.ntia.gov":3,
                       "seadog05.its.ntia.gov":2,
                       "seadog07.its.ntia.gov":1,
                       "seadog14.its.ntia.gov":1,
                       "seadog08.its.ntia.gov":13,
                       "seadog09.its.ntia.gov":11,
                       "seadog19.its.ntia.gov":11,
                       "seadog12.its.ntia.gov":11,
                       "seadog22.its.ntia.gov":11,
                       "seadog06.its.ntia.gov":14,
                       "seadog16.its.ntia.gov":14,
                       "seadog10.its.ntia.gov":15,
                       "seadog32.its.ntia.gov":16,
                       "seadog42.its.ntia.gov":16}
DATABLOCK_PATTERN = "(?P<date>\d+-\d+-\d+)_(?P<sensor_hostname>\S*|-*).zip"

BLOCK_MONTH_PATTERN = r"(?P<year>\d+)-(?P<month>\d+)-\d+_\S+|-*.zip"
LTE_TTI_CONFIG_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                   r"resources/LTE-tti_config_2_subf_2.xlsx")
#Reference Waveform Build 
# this is based on LTE config 2, special config 7 as per dhagle.in/LTE
a = np.append(np.ones(3*14*4+10*4),np.zeros(4*4+14*4))
LTE_27=pd.Series(np.roll(np.append(a,a),167))

# -----------------------------------------------------------------------------
# Module Functions
def get_sensor_ip_from_name(sensor_name,date = datetime.datetime.now(datetime.timezone.utc)):
    """Returns  the sensor_ip from the name for a given date range fixes the fact that NUCs and 
    IPs were changed due to failures.
    Catalina was 12/10, GMM was 02/14"""

    SENSOR_COMMON_NAMES = {"seadog03.its.ntia.gov":"Midway",
                       "seadog04.its.ntia.gov":"HU",
                       "seadog05.its.ntia.gov":"NIT",
                       "seadog07.its.ntia.gov":"GMM",
                       "seadog08.its.ntia.gov":"Pendleton",
                       "seadog09.its.ntia.gov":"Catalina-Omni",
                       "seadog19.its.ntia.gov":"Catalina-Directional",
                       "seadog06.its.ntia.gov":"CBBT-Omni",
                       "seadog16.its.ntia.gov":"CBBT-Directional",
                       "seadog10.its.ntia.gov":"Oceana",
                       "seadog32.its.ntia.gov":"PtLoma-Omni",
                       "seadog42.its.ntia.gov":"PtLoma-Directional"}
    
    if date > pd.to_datetime("2024-12-10 17:00",utc=True) and "Catalina" in sensor_name :
        SENSOR_COMMON_NAMES = {"seadog12.its.ntia.gov":"Catalina-Omni",
                        "seadog22.its.ntia.gov":"Catalina-Directional"}
    if date > pd.to_datetime("2025-02-14",utc=True) and "GMM" in sensor_name:
        SENSOR_COMMON_NAMES = {"seadog14.its.ntia.gov":"GMM"}
    SENSOR_IP_NAMES = {value:key for key,value in SENSOR_COMMON_NAMES.items() }
    assert sensor_name in SENSOR_IP_NAMES.keys(), f"Invalid sensor name {sensor_name}"
    return SENSOR_IP_NAMES[sensor_name]

def roll_max(query,reference):
    qidx = np.diff(query).argmax()
    ridx = np.diff(reference).argmax()
    query_shift = np.roll(query,ridx-qidx)
    return query_shift.flatten()

def lin_sum(array):
    alin = 10**(array/10)
    alin = alin.sum()
    return 10*np.log10(alin)

def fetch_lte_template(file_path = LTE_TTI_CONFIG_PATH):
    ## Importing the Resource Element Utilization of LTE
    # The LTE xlsx were built by transcribing from: https://dhagle.in/LTE.php
    # The LTE xslx contain positional RE values: 1 for Control Channel, d for Downlink Shared Channel,
    # u for Uplink Shared Channel, r for reserved Channel


    base =pd.read_excel(file_path,sheet_name = 0,header=None) 
    mid = pd.read_excel(file_path,sheet_name = 1,header=None)

    bc = base.replace(['d','u','r'],[0,0,0])
    mc = mid.replace(['d','u','r'],[0,0,0])

    bce = pd.concat([bc,bc,bc,bc],axis=1)
    bce = bce.T.sort_index().reset_index(drop=True).T

    mce = pd.concat([mc,mc,mc,mc],axis=1)
    mce = mce.T.sort_index().reset_index(drop=True).T

    #ps_pfp_20 is the time axis RE utilization for 10 MHz of a 20 MHz allocation
    # RE utilization is symmetric for the lower and upper portion of an allocation 
    ps_pfp_20 = 47*bce.sum(axis=0)+3*mce.sum(axis=0)
    ps_pfp_20 = ps_pfp_20.replace(0,0.1)

    #ps_pfp_10 is the time axis RE utilization for the 10 MHz allocation
    # RE utilization is symmetric for the lower and upper portion of an allocation 

    ps_pfp_10 = 44*bce.sum(axis=0)+6*mce.sum(axis=0)
    ps_pfp_10 = ps_pfp_10.replace(0,0.1)

    #ps_psd_20 is the frequency projection of RE utilization for the Lower 10 MHz of the 20 MHz allocation, 
    #Note that this is not symmetric for the Upper 10 MHz. the Upper complement is  ps_psd_20[::-1]
    ps_psd_20 = np.append(np.tile(bc.sum(axis=1),47),np.tile(mc.sum(axis=1),3))

    #ps_psd_10 is the frequency project of RE utilization of the 10 MHz allocation 
    ps_psd_10 = np.append(np.append(np.tile(bc.sum(axis=1),22),np.tile(mc.sum(axis=1),6)),np.tile(bc.sum(axis=1),22))
    #Frequency components of the RE utilization, note that the Upper 10 of 20 MHz compliment can be defined
    #with a frequency shift
    ps_freq_10 = np.arange(-15e3*300+7.5e3,15e3*300,15e3)
    ps_freq_20 = np.arange(-15e3*600+7.5e3,0,15e3)+5e6   

    output ={}
    output["ps_freq_10"] = ps_freq_10
    output["ps_freq_20"] = ps_freq_20
    output["ps_pfp_20"] = ps_pfp_20
    return output

#normalizes a vector that is in form of a pandas Series/DataFrame
def norm(x):
    xmin = x.min()
    xmax = x.max()
    return (x-xmin)/(xmax-xmin)
#input x: the PFP vector as row in a Pandas DataFrame
#input r: the reference waveform as a Pandas Series
    #in this case LTE Config 2, Special Config 7, scaled from 1 - 0 on the same vector axis as a pfp
#windowsize is the integer to perform a rolling max over, 28 corresponds to 1 slot//
#norm(x) returns a normalized vector. 

def corr_coeff_window(x,r,windowsize = 28):
    start_int = windowsize-1
    xr = norm(x).rolling(window=windowsize).max()[start_int:]
    rr = r.rolling(window=windowsize).max()[start_int:]
    correlation = signal.correlate(rr-np.mean(rr),xr-np.mean(xr))
    lag = correlation.argmax()-(len(rr) - 1)
    x_corrected = np.roll(x,lag)
    return x_corrected
# -----------------------------------------------------------------------------
# Module Classes
class DataProduct():
    """Wraps the sea_ingest dictionary of pandas data frames that represents a single acquistion of the sea sensor  """
    def __init__(self,data,**options) -> None:
        if isinstance(data,str):
            if re.search(".sigmf",data):
                self.data = sea_ingest.read_seamf(data)
                self.path = data
        elif isinstance(data,dict):
            self.data = data
            self.path = data

        self.psd_statistics = self.data['psd'].droplevel("datetime").droplevel("frequency").index.unique().tolist()
        self.frequencies = self.data['psd'].droplevel("datetime").droplevel("capture_statistic").index.unique().tolist()
        self.timestamps = self.data['psd'].droplevel("frequency").droplevel("capture_statistic").index.unique().tolist()
        self.pvt_detectors = self.data['pvt'].droplevel("datetime").droplevel("frequency").index.unique().tolist()
        self.pfp_detectors = self.data['pfp'].droplevel("datetime").droplevel("frequency").droplevel('capture_statistic').index.unique().tolist()
        self.pfp_statistics =self.data['pfp'].droplevel("datetime").droplevel("frequency").droplevel('detector').index.unique().tolist()
        self.channel_indices = self.data['channel_metadata'].index.tolist()
        self.gains  = self.data["channel_metadata"].droplevel('datetime')["cal_gain_dB"]
        self.noise_figures  = self.data["channel_metadata"].droplevel('datetime')["cal_noise_figure_dB"]
        
    def get_channel_index(self,channel):
        # Handle Channel Selection
        if isinstance(channel,int):
            channel_index = list(self.channel_indices[channel])
        elif isinstance(channel,float):
            channel_index = list(self.channel_indices[self.frequencies.index(channel)])
        else:
            channel_index = channel
        return channel_index

    def get_xy_data(self,channel,data_product,capture_statistic=None,detector=None):
        """Returns x_values, y_values for the selected channel, data_product and optional capture_statistic and detector"""
        channel_index = self.get_channel_index(channel)
        #print(f"Channel index is {channel_index}")
        if data_product == 'psd':
            assert capture_statistic != None, "must enter a capture statistic, see self.psd_statistics for options"
            index = channel_index
            index.append(capture_statistic)
            index = tuple(index)
            x_values = self.data['psd'].xs(index).index
            y_values = self.data['psd'].xs(index).values
            return x_values,y_values
        elif data_product == 'pfp':
            assert capture_statistic != None, "must enter a capture statistic, see self.pfp_statistics for options"
            assert detector != None, "must enter a detector, see self.pfp_detectors for options"
            index = channel_index
            index.append(capture_statistic)
            index.append(detector)
            index = tuple(index)
            x_values = self.data['pfp'].xs(index).index
            y_values = self.data['pfp'].xs(index).values
            return x_values,y_values
        elif data_product == 'pvt':
            assert detector != None, "must enter a detector, see self.pvt_detectors for options"
            index = channel_index
            index.append(detector)
            index = tuple(index)
            x_values = self.data['pvt'].xs(index).index
            y_values = self.data['pvt'].xs(index).values
            return x_values,y_values
        elif data_product == 'apd':
            index = channel_index
            index = tuple(index)
            x_values = self.data['apd'].xs(index).values
            y_values = self.data['apd'].xs(index).index
            return x_values,y_values 
        else:
            print(f"Unable to complete the request {locals()} did not have the required information")
            return None, None   
        
class DayBlock():
    def __init__(self, repository=None, sensor_name=None,date =None,file_path =None) -> None:
        if file_path:
            self.path = file_path
            basename = os.path.basename(file_path)
            match = re.match(DATABLOCK_PATTERN,basename)
            sensor_name = match.groupdict()["sensor_hostname"]
            date = match.groupdict()["date"]
        else:
            self.path = os.path.join(repository,f"{date}_{sensor_name}.zip")
        if sensor_name in SENSOR_COMMON_NAMES.keys():
            self.sensor_hostname = sensor_name
            self.sensor = SENSOR_COMMON_NAMES[sensor_name]
        elif sensor_name in SENSOR_COMMON_NAMES.values():
            self.sensor_hostname = get_sensor_ip_from_name(sensor_name)
            self.sensor = sensor_name
        self.date = date
        self.data = sea_ingest.read_seamf_zipfile(self.path)
        self.psd_statistics = self.data['psd'].droplevel("datetime").droplevel("frequency").index.unique().tolist()
        self.frequencies = self.data['psd'].droplevel("datetime").droplevel("capture_statistic").index.unique().tolist()
        self.timestamps = self.data['psd'].droplevel("frequency").droplevel("capture_statistic").index.unique().tolist()
        self.pvt_detectors = self.data['pvt'].droplevel("datetime").droplevel("frequency").index.unique().tolist()
        self.pfp_detectors = self.data['pfp'].droplevel("datetime").droplevel("frequency").droplevel('capture_statistic').index.unique().tolist()
        self.pfp_statistics =self.data['pfp'].droplevel("datetime").droplevel("frequency").droplevel('detector').index.unique().tolist()
        self.channel_indices = self.data['channel_metadata'].index.tolist()
        self.gains  = self.data["channel_metadata"].droplevel('datetime')["cal_gain_dB"]
        self.noise_figures  = self.data["channel_metadata"].droplevel('datetime')["cal_noise_figure_dB"]
        self.number_collects = len(self.data['sweep_metadata'])
        self.number_channels = len(self.frequencies)

    def get_single(self,single_selector):
        """Returns a  dictionary of a single collect"""
        if isinstance(single_selector,str):
            try:
                single_selector = pd.to_datetime(single_selector,utc=True)
            except:
                try:
                    single_selector = int(single_selector)
                except:
                    print(f"Could not decode {single_selector}")
                    raise
        if isinstance(single_selector,pd._libs.tslibs.timestamps.Timestamp):
            single_selector = np.argmin(abs(pd.to_datetime(self.data['sweep_metadata']['datetime'])-single_selector))

        start_index = single_selector*self.number_channels
        stop_index = (single_selector+1)*self.number_channels
        out_data = {} 
        out_data["psd"] = self.data["psd"][start_index*len(self.psd_statistics):stop_index*len(self.psd_statistics)]
        out_data["pvt"] = self.data["pvt"][start_index*len(self.pvt_detectors):stop_index*len(self.pvt_detectors)]
        out_data["pfp"] = self.data["pfp"][start_index*len(self.pfp_detectors)*len(self.pfp_statistics):stop_index*len(self.pfp_detectors)*len(self.pfp_statistics)]
        out_data["apd"] = self.data["apd"][start_index:stop_index]
        out_data["channel_metadata"] = self.data["channel_metadata"][start_index:stop_index]
        out_data["sweep_metadata"]= self.data["sweep_metadata"][single_selector:single_selector+1]
        sensor_metadata = dict(self.data["sensor_metadata"])
        sensor_metadata.update({"sensor":self.sensor,"sensor_hostname":self.sensor_hostname,"date":self.date})
        out_data["sensor_metadata"] = sensor_metadata
        return out_data
    
    def get_day_psd(self,capture_statistic = "mean", save = False,save_type = 'csv'):
        """Returns a pandas dataframe with index = 'sweep_timestamp' and columns = Frequency"""
        sweep_times = self.data["sweep_metadata"]["datetime"].unique()
        data_list = []
        for sweep_index,sweep_time in enumerate(sweep_times):
            slice_data = self.get_single(sweep_index)
            data_product = DataProduct(slice_data)
            data_dict = {}
            data_dict["sweep_timestamp"]=sweep_time

            for frequency in data_product.frequencies:
                columns,values = data_product.get_xy_data(data_product="psd",channel=frequency,capture_statistic=capture_statistic)
                columns = columns+frequency
                data_dict.update(dict(zip(columns,values)))
            data_list.append(data_dict)
        psd_df = pd.DataFrame(data_list)
        psd_df["sweep_timestamp"] = pd.to_datetime(psd_df["sweep_timestamp"])
        psd_df=psd_df.set_index("sweep_timestamp")
        if save:
            if re.search("csv",save_type,re.IGNORECASE):
                psd_df.to_csv(save)
            elif re.search("feather",save_type,re.IGNORECASE):
                psd_df.to_feather(save)
            elif re.search("parquet",save_type):
                psd_df.to_parquet(save)
            elif re.search("pickle",save_type,re.IGNORECASE):
                psd_df.to_pickle(save)
        return psd_df
    
    def get_aligned_pfp(self,channel,capture_statistic='mean',detector='rms',save = False,save_type='csv'):
        """Returns a dataframe with sweep_timestamp, channel,  and an aligned pfp stream """
        if channel in self.frequencies:
            frequency = channel
        elif isinstance(channel,int):
            frequency = self.frequencies[channel]
        else:
            frequency = float(channel)

        template = fetch_lte_template()
        ps_pfp_20 = template['ps_pfp_20']
        dm = self.data['pfp'].xs((frequency,capture_statistic,detector),level=('frequency','capture_statistic','detector'))
        droll = dm.apply(lambda x: roll_max(x,ps_pfp_20),axis=1,result_type='expand')
        droll=droll.T.apply(lambda x: corr_coeff_window(x,LTE_27)).T
        if save:
            if re.search("csv",save_type,re.IGNORECASE):
                droll.to_csv(save)
            elif re.search("feather",save_type,re.IGNORECASE):
                droll.to_feather(save)
            elif re.search("parquet",save_type):
                droll.to_parquet(save)
            elif re.search("pickle",save_type,re.IGNORECASE):
                droll.to_pickle(save)
        return droll

    def get_day_aligned_pfp(self,capture_statistic='mean',detector='rms',save = False,save_type='csv'):
        """Returns a dataframe with sweep_timestamp, channel,  and an aligned pfp stream """
        template = fetch_lte_template()

        for channel_index,frequency in enumerate(self.frequencies):
            ps_pfp_20 = template['ps_pfp_20']
            dm = self.data['pfp'].xs((frequency,capture_statistic,detector),level=('frequency','capture_statistic','detector'))
            droll = dm.apply(lambda x: roll_max(x,ps_pfp_20),axis=1,result_type='expand')
            droll = droll.T.apply(lambda x: corr_coeff_window(x,LTE_27)).T
            droll.insert(0,"frequency",frequency*np.ones(len(dm.index)))
            if channel_index == 0:
                day_store = droll.copy()
            else:
                day_store = pd.concat([day_store,droll])
        if save:
            if re.search("csv",save_type,re.IGNORECASE):
                day_store.to_csv(save)
            elif re.search("feather",save_type,re.IGNORECASE):
                day_store.to_feather(save)
            elif re.search("parquet",save_type):
                day_store.to_parquet(save)
            elif re.search("pickle",save_type,re.IGNORECASE):
                day_store.to_pickle(save)
        return day_store

        
          
class SummaryTable():
    def __init__(self,data,**options):
        if isinstance(data,str):
            self.data = pd.read_csv(data)
        elif isinstance(data,pd.core.frame.DataFrame):
            self.data =data
        self.data['timestamp'] = self.data['timestamp'].apply(pd.to_datetime)
        self.data['acquisition_timestamp'] = self.data['acquisition_timestamp'].apply(pd.to_datetime)
        self.data['PAPR'] = self.data['max']-self.data["mean"]
        self.sensor_names = self.data["sensor_name"].unique()
        self.sensor_hostnames = self.data["sensor_hostname"].unique()
        self.channel_frequencies = self.data["channel_frequency_mhz"].unique()
        
    def get_sensor_data(self,sensor):
        if sensor in self.sensor_hostnames:
            return self.data[self.data['sensor_hostname']==sensor]
        elif sensor in self.sensor_names:
            return self.data[self.data['sensor_name']==sensor]
        else:
            return self.data
            
    def get_sensor_channel_data(self,sensor,channel):
        if isinstance(channel,int):
            frequency = self.channel_frequencies[channel]
        elif channel in self.channel_frequencies:
            frequency = channel
        elif channel in 1e6*self.channel_frequencies:
            frequency = channel/1e6
            
        if sensor in self.sensor_hostnames:
            return self.data[(self.data['sensor_hostname']==sensor)&(self.data['channel_frequency_mhz']==frequency) ]
        elif sensor in self.sensor_names:
            return self.data[(self.data['sensor_name']==sensor)&(self.data['channel_frequency_mhz']==frequency) ]
        else:
            return self.data
        
    def get_sensor_channel_daterange_data(self,start_date,stop_date,sensor,channel):
        if isinstance(start_date,str):
            start_date = pd.to_datetime(start_date,utc = True)
        if isinstance(stop_date,str):
            start_date = pd.to_datetime(stop_date,utc = True)
        if isinstance(channel,int):
            frequency = self.channel_frequencies[channel]
        elif channel in self.channel_frequencies:
            frequency = channel
        elif channel in 1e6*self.channel_frequencies:
            frequency = channel/1e6
        if sensor in self.sensor_hostnames:
            return self.data[(self.data['sensor_hostname']==sensor)&(self.data['channel_frequency_mhz']==frequency) &(self.data['timestamp']>start_date)&(self.data['timestamp']<stop_date)]
        elif sensor in self.sensor_names:
            return self.data[(self.data['sensor_name']==sensor)&(self.data['channel_frequency_mhz']==frequency) &(self.data['timestamp']>start_date)&(self.data['timestamp']<stop_date) ]
        else:
            return self.data      
# -----------------------------------------------------------------------------
# Module Scripts
def create_summary_table_flat_files(top_directory,save_location = None,verbose =True,sort_timestamps=True, relative_filenames  = True):
    """ Creates the summary table from a directory of raw files. Returns a pandas dataframe."""
    data = []
    for root_directory,directories,file_names in os.walk(top_directory):
            for file_name in file_names:
                if verbose:
                    print(f'the file_name is {file_name}')
                if re.search(".sigmf",file_name,re.IGNORECASE):
                    fixed_data_row = {}
                    file_path = os.path.join(root_directory,file_name)
                    if verbose:
                        print(f'the file path is {file_path}')

                    try:
                        # Load data and metadata
                        metadata = sea_ingest.read_seamf_meta(file_path)
                        fixed_data_row['file'] = file_path
                        fixed_data_row["sensor_hostname"] = metadata.global_.sensor['sensor_spec']['id']
                        fixed_data_row["sensor_name"] = SENSOR_COMMON_NAMES[fixed_data_row["sensor_hostname"]]
                        fixed_data_row["sensor_id"] = SENSOR_IDS[fixed_data_row["sensor_hostname"]]
                        for capture_index,capture in enumerate(metadata.captures):
                            data_row = dict(fixed_data_row)
                            data_row["channel"] = capture_index
                            data_row["channel_frequency_mhz"] = capture['core:frequency']*1e-6
                            data_row["timestamp"] = pd.to_datetime(capture['core:datetime'])
                            data_row["acquisition_timestamp"] = pd.to_datetime(metadata.captures[0]['core:datetime'])
                            data_row["date"] = str(data_row["timestamp"].date())
                            data_row["max"]=metadata.global_.max_of_max_channel_powers[capture_index]
                            data_row["median"]=metadata.global_.median_channel_powers[capture_index]
                            data_row["mean"]=metadata.global_.mean_channel_powers[capture_index]
                            data_row["overload"] = capture['ntia-sensor:overload']
                            data.append(data_row)
                    except Exception as e:
                        print(e)
                        continue
    df = pd.DataFrame(data)
    if sort_timestamps:
        df['timestamp'] = pd.to_datetime(df['timestamp'])
        df.sort_values(by = ['timestamp'],inplace=True)
    if relative_filenames:
        df['file'] = df['file'].apply(lambda x:os.path.relpath(x,top_directory))
    if save_location:
        df.to_csv(save_location,index=False)      
    return df

def append_summary_table_flat_files(top_directory,current_summary_table,save_location = None,verbose =True,sort_timestamps = True,relative_filenames = False):
    """Appends files to the current_summary_table. The current_summary_table can be a path to a csv 
    (or other serialized table format) or a pandas DataFrame. Returns a pandas dataframe."""
    ## Handle current_data_table
    if isinstance(current_summary_table,str):
        if ".csv" in current_summary_table:
            current_data = pd.read_csv(current_summary_table)
        elif ".feather" in current_summary_table:
            current_data = pd.read_feather(current_summary_table)
    else:
        current_data = current_summary_table
    current_summary_table = current_data
    current_file_names = current_summary_table['file'].to_list()
    data = current_data.to_dict('records')
    # Same loop as create summary table with a continue if the file name is already in the table
    for root_directory,directories,file_names in os.walk(top_directory):
            for file_name in file_names:
                if verbose:
                    print(f'the file_name is {file_name}')
                if re.search(".sigmf",file_name,re.IGNORECASE):
                    fixed_data_row = {}
                    file_path = os.path.join(root_directory,file_name)
                    if file_path in current_file_names:
                        if verbose:
                            print(f'The file path is already in the table not appending: {file_path}')
                        continue
                    if verbose:
                        print(f'the file path is {file_path}')
                    try:
                        # Load data and metadata
                        metadata = sea_ingest.read_seamf_meta(file_path)
                        fixed_data_row['file'] = file_path
                        fixed_data_row["sensor_hostname"] = metadata.global_.sensor['sensor_spec']['id']
                        fixed_data_row["sensor_name"] = SENSOR_COMMON_NAMES[fixed_data_row["sensor_hostname"]]
                        fixed_data_row["sensor_id"] = get_sensor_ip_from_name(fixed_data_row["sensor_hostname"])
                        for capture_index,capture in enumerate(metadata.captures):
                            data_row = dict(fixed_data_row)
                            data_row["channel"] = capture_index
                            data_row["channel_frequency_mhz"] = capture['core:frequency']*1e-6
                            data_row["timestamp"] = pd.to_datetime(capture['core:datetime'])
                            data_row["date"] = str(data_row["timestamp"].date())
                            data_row["acquisition_timestamp"] = pd.to_datetime(metadata.captures[0]['core:datetime'])
                            data_row["max"]=metadata.global_.max_of_max_channel_powers[capture_index]
                            data_row["median"]=metadata.global_.median_channel_powers[capture_index]
                            data_row["median"]=metadata.global_.mean_channel_powers[capture_index]
                            data_row["overload"] = capture['ntia-sensor:overload']
                            data.append(data_row)
                    except Exception as e:
                        print(e)
                        continue
    df = pd.DataFrame(data)
    if sort_timestamps:
        df['timestamp'] = pd.to_datetime(df['timestamp'])
        df.sort_values(by = ['timestamp'],inplace=True)
    if relative_filenames:
        df['file'] = df['file'].apply(lambda x:os.path.relpath(x,top_directory))
    if save_location:
        df.to_csv(save_location,index=False)
    return df

def summarize_block(file_name,root_directory,verbose):
    data = []
    match = re.match(DATABLOCK_PATTERN,file_name)
    if match:
        fixed_data_row = {}
        sensor_name = match.groupdict()["sensor_hostname"]
        date = match.groupdict()["date"]
        if sensor_name in SENSOR_COMMON_NAMES.keys():
            sensor = SENSOR_COMMON_NAMES[sensor_name]
            sensor_hostname = sensor_name
        elif sensor_name in SENSOR_COMMON_NAMES.values():
            sensor = sensor_name
            sensor_hostname = get_sensor_ip_from_name(sensor_name)
        fixed_data_row["sensor_hostname"] = sensor_hostname
        fixed_data_row["date"] = date
        fixed_data_row["sensor_name"] = SENSOR_COMMON_NAMES[fixed_data_row["sensor_hostname"]]
        fixed_data_row["sensor_id"] = SENSOR_IDS[fixed_data_row["sensor_hostname"]]
        file_path = os.path.join(root_directory,file_name)
        zip_file = zipfile.ZipFile(file_path)
        for sigmf in zip_file.filelist:
            with zip_file.open(sigmf.filename) as infile:
                metadata = sea_ingest.read_seamf_meta(infile)
            if verbose:
                print(f'the file path is {file_path}')
            try:
                # Load data and metadata
                fixed_data_row['file'] = file_path

                for capture_index,capture in enumerate(metadata.captures):
                    data_row = dict(fixed_data_row)
                    data_row["channel"] = capture_index
                    data_row["channel_frequency_mhz"] = capture['core:frequency']*1e-6
                    data_row["timestamp"] = pd.to_datetime(capture['core:datetime'])
                    data_row["acquisition_timestamp"] = pd.to_datetime(metadata.captures[0]['core:datetime'])
                    data_row["max"]=metadata.global_.max_of_max_channel_powers[capture_index]
                    data_row["median"]=metadata.global_.median_channel_powers[capture_index]
                    data_row["mean"]=metadata.global_.mean_channel_powers[capture_index]
                    data_row["overload"] = capture['ntia-sensor:overload']
                    data.append(data_row)
            except Exception as e:
                print(e)
                continue
        return data
def summarize_block_calibration(file_name,root_directory,verbose):
    data = []
    match = re.match(DATABLOCK_PATTERN,file_name)
    if match:
        fixed_data_row = {}
        sensor_name = match.groupdict()["sensor_hostname"]
        date = match.groupdict()["date"]
        if sensor_name in SENSOR_COMMON_NAMES.keys():
            sensor = SENSOR_COMMON_NAMES[sensor_name]
            sensor_hostname = sensor_name
        elif sensor_name in SENSOR_COMMON_NAMES.values():
            sensor = sensor_name
            sensor_hostname = get_sensor_ip_from_name(sensor_name)
        fixed_data_row["sensor_hostname"] = sensor_hostname
        fixed_data_row["date"] = date
        fixed_data_row["sensor_name"] = SENSOR_COMMON_NAMES[fixed_data_row["sensor_hostname"]]
        fixed_data_row["sensor_id"] = SENSOR_IDS[fixed_data_row["sensor_hostname"]]
        file_path = os.path.join(root_directory,file_name)
        zip_file = zipfile.ZipFile(file_path)
        for sigmf in zip_file.filelist:
            with zip_file.open(sigmf.filename) as infile:
                metadata = sea_ingest.read_seamf_meta(infile)
            if verbose:
                print(f'the file path is {file_path}')
            try:
                # Load data and metadata
                fixed_data_row['file'] = file_path

                for capture_index,capture in enumerate(metadata.captures):
                    data_row = dict(fixed_data_row)
                    data_row["channel"] = capture_index
                    data_row["channel_frequency_mhz"] = capture['core:frequency']*1e-6
                    data_row["timestamp"] = pd.to_datetime(capture['core:datetime'])
                    data_row["acquisition_timestamp"] = pd.to_datetime(metadata.captures[0]['core:datetime'])
                    data_row["max"]=metadata.global_.max_of_max_channel_powers[capture_index]
                    data_row["median"]=metadata.global_.median_channel_powers[capture_index]
                    data_row["mean"]=metadata.global_.mean_channel_powers[capture_index]
                    data_row["overload"] = capture['ntia-sensor:overload']
                    data_row.update(capture["ntia-sensor:sensor_calibration"])
                    data_row.update(capture["ntia-sensor:sigan_settings"])
                    data.append(data_row)
            except Exception as e:
                print(e)
                continue
        return data
def create_calibration_summary(top_directory = None,file_names = None,save = None,
                                     verbose =False,sort_timestamps=True, relative_filenames  = True):
    """ Creates the summary table from a directory of raw files. Returns a pandas dataframe."""
    data = []
    if top_directory:
        for root_directory,directories,file_names in os.walk(top_directory):
                for file_name in file_names:
                    if re.search(".zip",file_name,re.IGNORECASE):
                        if verbose:
                            print(f'the file_name is {file_name}')
                        data_row = summarize_block_calibration(file_name,root_directory=root_directory,verbose=verbose)
                        data.extend(data_row)

    elif file_names:
            for file_name in file_names:
                if re.search(".zip",file_name,re.IGNORECASE):
                    root_directory = os.path.dirname(file_name)
                    file_name = os.path.basename(file_name)
                    if verbose:
                        print(f'the file_name is {file_name}')
                    data_row = summarize_block_calibration(file_name,root_directory=root_directory,verbose=verbose)
                    data.extend(data_row)
    df = pd.DataFrame(data)
    if sort_timestamps:
        df['timestamp'] = pd.to_datetime(df['timestamp'])
        df.sort_values(by = ['timestamp'],inplace=True)
    if relative_filenames:
        df['file'] = df['file'].apply(lambda x:os.path.relpath(x,os.path.dirname(x)))
    if save:
        df.to_csv(save,index=False)      
    return df
        
def create_summary_table_data_blocks(top_directory = None,file_names = None,save = None,
                                     verbose =False,sort_timestamps=True, relative_filenames  = True):
    """ Creates the summary table from a directory of raw files. Returns a pandas dataframe."""
    data = []
    if top_directory:
        for root_directory,directories,file_names in os.walk(top_directory):
                for file_name in file_names:
                    if re.search(".zip",file_name,re.IGNORECASE):
                        if verbose:
                            print(f'the file_name is {file_name}')
                        data_row = summarize_block(file_name,root_directory=root_directory,verbose=verbose)
                        data.extend(data_row)

    elif file_names:
            for file_name in file_names:
                if re.search(".zip",file_name,re.IGNORECASE):
                    root_directory = os.path.dirname(file_name)
                    file_name = os.path.basename(file_name)
                    if verbose:
                        print(f'the file_name is {file_name}')
                    data_row = summarize_block(file_name,root_directory=root_directory,verbose=verbose)
                    data.extend(data_row)
    df = pd.DataFrame(data)
    if sort_timestamps:
        df['timestamp'] = pd.to_datetime(df['timestamp'])
        df.sort_values(by = ['timestamp'],inplace=True)
    if relative_filenames:
        df['file'] = df['file'].apply(lambda x:os.path.relpath(x,os.path.dirname(x)))
    if save:
        df.to_csv(save,index=False)      
    return df

def summarize_by_month(top_directory,output_directory,exclude ="seadog08",include=None,force_new=False):
    "Reads top directory and organizes the summary by month of block names (may have some timestamps slightly after midnight)"
    file_names = os.listdir(top_directory)
    if include:
        file_names = [file_name for file_name in file_names if re.search(include,file_name,re.IGNORECASE)]
    if exclude:
        file_names = [file_name for file_name in file_names if not re.search(exclude,file_name,re.IGNORECASE)]
    block_files = list(filter(lambda x:re.match(BLOCK_MONTH_PATTERN,x),file_names))
    year_month_list = list(map(lambda x:"{year}_{month}".format(**re.match(BLOCK_MONTH_PATTERN,x).groupdict()),block_files)) 
    unique_months = list(set(year_month_list))
    month_dictionary = {month:[] for month in unique_months}
    destination_names = list(map(lambda x: os.path.join(output_directory,x),os.listdir(output_directory)))
    for index,year_month in enumerate(sorted(year_month_list)):
        month_dictionary[year_month].append(os.path.join(top_directory,block_files[index]))
    for key,value in month_dictionary.items():
        save_path = os.path.join(output_directory,key+".csv")
        if not force_new:
            if save_path in destination_names:
                continue
        create_summary_table_data_blocks(file_names=value,
                                         save=save_path)
        
def copy_and_rename(production_directory,output_directory,exclude = "seadog08|seadog10",include=None,force_new = False):
    """Opens a raw production directory and copies the contents to the teir2 data structure, updating the sensor name"""
    file_names = os.listdir(production_directory)
    if include:
        file_names = list(filter(lambda x:re.search(include,x),file_names))
    if exclude:
        file_names = list(filter (lambda x:not re.search(exclude,x),file_names))
    block_files = list(filter(lambda x:re.match(DATABLOCK_PATTERN,x),file_names))
    date_sensor_list = list(map(lambda x: re.match(DATABLOCK_PATTERN,x).groupdict(),block_files))
    destination_names = list(map(lambda x: os.path.join(output_directory,x),os.listdir(output_directory)))
    for day_sensor in date_sensor_list:
        clean_date = pd.to_datetime(day_sensor["date"])
        clean_date = clean_date.date()
        old_file_path = os.path.join(production_directory,f'{day_sensor["date"]}_{day_sensor["sensor_hostname"]}.zip')

        try:
            sensor_name = SENSOR_COMMON_NAMES[day_sensor["sensor_hostname"]]
        except KeyError:
            print(f"The file {old_file_path} has failed")
            continue
        new_file_path = os.path.join(output_directory,f'{clean_date}_{sensor_name}.zip')
        if not force_new:
            if new_file_path in destination_names:
                continue
        #print(old_file_path,new_file_path)
        try:
            shutil.copyfile(old_file_path,new_file_path)
        except Exception as e:
            print(e)

def save_all_psd(top_directory,output_directory,capture_statistics=["mean","median","95th_percentile","99th_percentile","max"],exclude=None,include=None,force_new = False):
    file_names = os.listdir(top_directory)
    if include:
        file_names = [file_name for file_name in file_names if re.search(include,file_name,re.IGNORECASE)]
    if exclude:
        file_names = [file_name for file_name in file_names if not re.search(exclude,file_name,re.IGNORECASE)]
    block_files = list(filter(lambda x:re.match(BLOCK_MONTH_PATTERN,x),file_names))
    destination_names=[]
    if not force_new:
        destination_names = os.listdir(output_directory)
        destination_names = list(map(lambda x:os.path.join(output_directory,x),destination_names))
    for file_name in block_files:
        match = re.match(DATABLOCK_PATTERN,file_name)
        sensor_name = match.groupdict()["sensor_hostname"]
        date = match.groupdict()["date"]
        if sensor_name in SENSOR_COMMON_NAMES.keys():
            sensor = SENSOR_COMMON_NAMES[sensor_name]
        elif sensor_name in SENSOR_COMMON_NAMES.values():
            sensor = sensor_name
        for capture_statistic in capture_statistics:
            psd_name = f"{date}_{sensor}_{capture_statistic}.csv"
            psd_path = os.path.join(output_directory,psd_name)
            if not force_new:
                if psd_path in destination_names:
                    continue
            try:
                day_block = DayBlock(file_path=os.path.join(top_directory,file_name))
                day_block.get_day_psd(capture_statistic=capture_statistic,save=psd_path)
            except Exception as e:
                print(f'File:{os.path.join(top_directory,file_name)} failed')
                print(e)

def save_all_pfp(top_directory,output_directory,capture_statistics=["mean"], 
                 detectors =["rms"],exclude=None, include=None,force_new = False):
    file_names = os.listdir(top_directory)
    if include:
        file_names = [file_name for file_name in file_names if re.search(include,file_name,re.IGNORECASE)]
    if exclude:
        file_names = [file_name for file_name in file_names if not re.search(exclude,file_name,re.IGNORECASE)]
    block_files = list(filter(lambda x:re.match(BLOCK_MONTH_PATTERN,x),file_names))
    destination_names=[]
    if not force_new:
        destination_names = os.listdir(output_directory)
        destination_names = list(map(lambda x:os.path.join(output_directory,x),destination_names))
    for file_name in block_files:
        match = re.match(DATABLOCK_PATTERN,file_name)
        sensor_name = match.groupdict()["sensor_hostname"]
        date = match.groupdict()["date"]
        if sensor_name in SENSOR_COMMON_NAMES.keys():
            sensor = SENSOR_COMMON_NAMES[sensor_name]
        elif sensor_name in SENSOR_COMMON_NAMES.values():
            sensor = sensor_name
        for capture_statistic in capture_statistics:
            for detector in detectors:
                pfp_name = f"PFP_{date}_{sensor}_{capture_statistic}_{detector}.csv"
                pfp_path = os.path.join(output_directory,pfp_name)
                if not force_new:
                    if pfp_path in destination_names:
                        continue
                try:
                    day_block = DayBlock(file_path=os.path.join(top_directory,file_name))
                    day_block.get_day_aligned_pfp(capture_statistic=capture_statistic,detector=detector,save=pfp_path)
                except Exception as e:
                    print(f'file: {os.path.join(top_directory,file_name)} failed')
                    print(e)


def test_aligned_pfp(test_data = r".\test data\2024-7-4_seadog07.its.ntia.gov.zip"):
    dayblock = DayBlock(file_path=test_data)
    print(dayblock.sensor_hostname)
    pfp = dayblock.get_aligned_pfp(4)
    print(pfp)

def test_day_aligned_pfp(test_data = r".\test data\2024-7-4_seadog07.its.ntia.gov.zip"):
    dayblock = DayBlock(file_path=test_data)
    pfp = dayblock.get_day_aligned_pfp()
    print(pfp)
# -----------------------------------------------------------------------------
# Module Runner
if __name__=="__main__":
    #summarize_by_month(r"C:\Users\sandersa\Box\SEA-Tier2 - REV1\Raw Data",r"C:\Users\sandersa\Box\SEA-Tier2 - REV1\Summaries",force_new=True)
    #copy_and_rename(r"C:\Users\sandersa\Box\Production Data",r"D:\SEA\test_zip_files")
    # test_aligned_pfp()
    #test_day_aligned_pfp()
    #save_all_psd(r"C:\Users\sandersa\Box\SEA-Tier2 - REV1\Raw Data",r"C:\Users\sandersa\Box\SEA-Tier2 - REV1\PSD")
    #save_all_pfp(r"C:\Users\sandersa\Box\SEA-Tier2 - REV1\Raw Data",r'C:\Users\sandersa\Box\SEA-Tier2 - REV1\PFP Aligned')
    print("Currently this module does nothing when run as a script, but test functions are available to run individual pieces of functionality. See the function definitions for more details.")
