[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "nasctn-sea-visualization"
dynamic = ["version"]
description = 'Tools to open, reshape and visualize data from the NASCTN CBRS SEA program.'
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
  { name = "sandersa", email = "aric.sanders@nist.gov" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "nasctn-sea-ingest @ git+https://github.com/usnistgov/nasctn-sea-ingest@1.0.0",
]

[project.urls]
Documentation = "https://github.com/sandersa/nasctn-sea-visualization#readme"
Issues = "https://github.com/sandersa/nasctn-sea-visualization/issues"
Source = "https://github.com/sandersa/nasctn-sea-visualization"

[tool.hatch.version]
path = "nasctn_sea_visualization/__init__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:nasctn_sea_visualization tests}"

[tool.coverage.run]
source_pkgs = ["nasctn_sea_visualization", "tests"]
branch = true
parallel = true
omit = [
  "nasctn_sea_visualization/__about__.py",
]

[tool.coverage.paths]
nasctn_sea_visualization = ["nasctn_sea_visualization", "*/nasctn-sea-visualization/nasctn_sea_visualization"]
tests = ["tests", "*/nasctn-sea-visualization/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
